#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="${PROJECT_DIR}/config.yaml"
ENV_FILE="${PROJECT_DIR}/.env"

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "ERROR: config.yaml not found at $CONFIG_FILE" >&2
    exit 1
fi

if ! command -v yq &> /dev/null; then
    echo "ERROR: yq is required but not installed" >&2
    exit 1
fi

# Load existing secrets if .env exists (to preserve them across deploys)
declare -A EXISTING_SECRETS
if [[ -f "$ENV_FILE" ]]; then
    while IFS='=' read -r key value; do
        [[ -z "$key" || "$key" == \#* ]] && continue
        EXISTING_SECRETS["$key"]="$value"
    done < "$ENV_FILE"
fi

generate_secret() {
    openssl rand -hex 32
}

generate_api_key() {
    # LiveKit API keys are shorter, alphanumeric
    openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | head -c 12
}

get_or_generate() {
    local key="$1"
    local generator="${2:-generate_secret}"
    if [[ -n "${EXISTING_SECRETS[$key]:-}" ]]; then
        echo "${EXISTING_SECRETS[$key]}"
    else
        $generator
    fi
}

# Extract config values with yq
DOMAIN=$(yq '.domain' "$CONFIG_FILE")
SUBDOMAIN_MATRIX=$(yq '.subdomains.matrix' "$CONFIG_FILE")
SUBDOMAIN_ELEMENT=$(yq '.subdomains.element' "$CONFIG_FILE")
SUBDOMAIN_LIVEKIT=$(yq '.subdomains.livekit' "$CONFIG_FILE")
SUBDOMAIN_TURN=$(yq '.subdomains.turn' "$CONFIG_FILE")

VPS_HOST=$(yq '.vps.host' "$CONFIG_FILE")

S3_MEDIA_ENDPOINT=$(yq '.s3.media.endpoint' "$CONFIG_FILE")
S3_MEDIA_BUCKET=$(yq '.s3.media.bucket' "$CONFIG_FILE")
S3_MEDIA_ACCESS_KEY=$(yq '.s3.media.access_key' "$CONFIG_FILE")
S3_MEDIA_SECRET_KEY=$(yq '.s3.media.secret_key' "$CONFIG_FILE")

S3_BACKUP_ENDPOINT=$(yq '.s3.backup.endpoint' "$CONFIG_FILE")
S3_BACKUP_BUCKET=$(yq '.s3.backup.bucket' "$CONFIG_FILE")
S3_BACKUP_ACCESS_KEY=$(yq '.s3.backup.access_key' "$CONFIG_FILE")
S3_BACKUP_SECRET_KEY=$(yq '.s3.backup.secret_key' "$CONFIG_FILE")

MAX_UPLOAD_SIZE_MB=$(yq '.media_cache.max_upload_size_mb' "$CONFIG_FILE")
MEDIA_CLEANUP_CRON=$(yq '.media_cache.cleanup_cron' "$CONFIG_FILE")
MIN_FREE_GB=$(yq '.media_cache.min_free_gb' "$CONFIG_FILE")

COTURN_UDP_PORT_RANGE=$(yq '.coturn.udp_port_range' "$CONFIG_FILE")
COTURN_MIN_PORT="${COTURN_UDP_PORT_RANGE%-*}"
COTURN_MAX_PORT="${COTURN_UDP_PORT_RANGE#*-}"

BACKUP_CRON=$(yq '.backup.cron' "$CONFIG_FILE")
BACKUP_RETENTION_DAYS=$(yq '.backup.retention_days' "$CONFIG_FILE")

# Generate or preserve secrets
POSTGRES_PASSWORD=$(get_or_generate POSTGRES_PASSWORD)
SYNAPSE_REGISTRATION_SHARED_SECRET=$(get_or_generate SYNAPSE_REGISTRATION_SHARED_SECRET)
SYNAPSE_MACAROON_SECRET_KEY=$(get_or_generate SYNAPSE_MACAROON_SECRET_KEY)
SYNAPSE_FORM_SECRET=$(get_or_generate SYNAPSE_FORM_SECRET)
LIVEKIT_API_KEY=$(get_or_generate LIVEKIT_API_KEY generate_api_key)
LIVEKIT_API_SECRET=$(get_or_generate LIVEKIT_API_SECRET)
COTURN_AUTH_SECRET=$(get_or_generate COTURN_AUTH_SECRET)

# Write complete .env
cat > "$ENV_FILE" << EOF
# Auto-generated by generate-env.sh — do not edit manually
# Re-running this script preserves existing secret values

# Domain
DOMAIN="${DOMAIN}"
SUBDOMAIN_MATRIX="${SUBDOMAIN_MATRIX}"
SUBDOMAIN_ELEMENT="${SUBDOMAIN_ELEMENT}"
SUBDOMAIN_LIVEKIT="${SUBDOMAIN_LIVEKIT}"
SUBDOMAIN_TURN="${SUBDOMAIN_TURN}"

# VPS
VPS_EXTERNAL_IP="${VPS_HOST}"

# S3 Media
S3_MEDIA_ENDPOINT="${S3_MEDIA_ENDPOINT}"
S3_MEDIA_BUCKET="${S3_MEDIA_BUCKET}"
S3_MEDIA_ACCESS_KEY="${S3_MEDIA_ACCESS_KEY}"
S3_MEDIA_SECRET_KEY="${S3_MEDIA_SECRET_KEY}"

# S3 Backup
S3_BACKUP_ENDPOINT="${S3_BACKUP_ENDPOINT}"
S3_BACKUP_BUCKET="${S3_BACKUP_BUCKET}"
S3_BACKUP_ACCESS_KEY="${S3_BACKUP_ACCESS_KEY}"
S3_BACKUP_SECRET_KEY="${S3_BACKUP_SECRET_KEY}"

# Media cache
MAX_UPLOAD_SIZE_MB="${MAX_UPLOAD_SIZE_MB}"
MEDIA_CLEANUP_CRON="${MEDIA_CLEANUP_CRON}"
MIN_FREE_GB="${MIN_FREE_GB}"

# coturn
COTURN_MIN_PORT="${COTURN_MIN_PORT}"
COTURN_MAX_PORT="${COTURN_MAX_PORT}"
COTURN_AUTH_SECRET="${COTURN_AUTH_SECRET}"

# Backup
BACKUP_CRON="${BACKUP_CRON}"
BACKUP_RETENTION_DAYS="${BACKUP_RETENTION_DAYS}"

# Secrets (auto-generated, preserved across deploys)
POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
SYNAPSE_REGISTRATION_SHARED_SECRET="${SYNAPSE_REGISTRATION_SHARED_SECRET}"
SYNAPSE_MACAROON_SECRET_KEY="${SYNAPSE_MACAROON_SECRET_KEY}"
SYNAPSE_FORM_SECRET="${SYNAPSE_FORM_SECRET}"
LIVEKIT_API_KEY="${LIVEKIT_API_KEY}"
LIVEKIT_API_SECRET="${LIVEKIT_API_SECRET}"
EOF

chmod 600 "$ENV_FILE"
echo "Environment file written to $ENV_FILE"
